## NumPy Basics Exercise 

In [159]:
# Import NumPy as its abbreviation 'np'

import numpy as np

In [11]:
# Create a 1-dimensional NumPy array using np.array()
a1 =np.array([1,2,3])
a1

array([1, 2, 3])

In [12]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[4,5,6],
             [7,8,9]])
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[10,11,12],
               [13,14,15],
               [16,17,18]],
                
               [[19,20,21],
               [22,23,24],
               [25,26,27]],
                
               [[28,29,30],
               [31,32,33],
               [34,35,36]]])
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [128]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

a1.ndim, a1.shape, a1.dtype, a1.size, type(a1)

(1, (3,), dtype('int32'), 3, numpy.ndarray)

In [129]:
# Attributes of 2-dimensional array

a2.ndim, a2.shape, a2.dtype, a2.size, type(a2)

(2, (2, 3), dtype('int32'), 6, numpy.ndarray)

In [130]:
# Attributes of 3-dimensional array
a3.ndim, a3.shape, a3.dtype, a3.size, type(a3)

(3, (3, 3, 3), dtype('int32'), 27, numpy.ndarray)

In [40]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  4  5  6
1  7  8  9

In [43]:
# Create an array of shape (10, 2) with only ones

ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:

# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [131]:
# Create an array within a range of 0 and 100 with step 3


a4 = np.arange(0,100,3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [132]:

# Create a random array with numbers between 0 and 10 of size (7, 2)


a5 =  np.random.randint(10, size=(7,2))
a5

array([[3, 7],
       [5, 7],
       [0, 7],
       [3, 0],
       [7, 3],
       [5, 7],
       [3, 2]])

In [133]:

# Create a random array of floats between 0 & 1 of shape (3, 5)

a6 = np.random.random((3,5))
a6

array([[0.37228277, 0.94013344, 0.97366384, 0.28392097, 0.30536386],
       [0.48561375, 0.44842414, 0.99445746, 0.17592525, 0.01807536],
       [0.49389372, 0.17882271, 0.36646878, 0.74417052, 0.72093992]])

In [62]:

# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.randint(0,10, size= (4,6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [69]:

# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8 = np.random.randint(1,10, size=(3,7))
a8



array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6],
       [2, 9, 5, 6, 4, 7, 9]])

In [70]:
# Find the unique numbers in the array you just create

np.unique(a8)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [134]:
# Find the 0'th index of the latest array you created

a8[0]

array([7, 9, 3, 7, 1, 4, 4])

In [74]:

# Get the first 2 rows of latest array you created

a8[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [136]:
# Get the first 2 values of the first 2 rows of the latest array

a8[:2, :2]

array([[7, 9],
       [5, 7]])

In [85]:

# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

a9 = np.random.randint(0,10, size=(3,5))
a9

array([[5, 6, 3, 6, 7],
       [0, 5, 7, 4, 3],
       [1, 5, 5, 0, 8]])

In [137]:
ones_a = np.ones((3,5))
ones_a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [142]:
# Add the two arrays together

a11 = a9 + ones_a
a11 

array([[6., 7., 4., 7., 8.],
       [1., 6., 8., 5., 4.],
       [2., 6., 6., 1., 9.]])

In [141]:
# Create another array of ones of shape (5, 3)
array = np.ones((5,3))
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [144]:
# Try add the array of ones and the other most recent array together

array_add = a11 + array
array_add

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [90]:
# using trnapose to add the array 

array_add = a11 + array.T
array_add

array([[16.,  8.,  6., 16., 17.],
       [ 7.,  9.,  3., 16.,  9.],
       [14., 10.,  7.,  1.,  7.]])

In [145]:
# Create another array of ones of shape (3, 5)

array_1 = np.ones((3,5))
array_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [146]:
# Subtract the new array of ones from the other most recent array


array_sub = array_add - array_1
array_sub

array([[6., 7., 4., 7., 8.],
       [1., 6., 8., 5., 4.],
       [2., 6., 6., 1., 9.]])

In [147]:
# Multiply the ones array with the latest array


array_mul = array_add * array_sub
array_mul

array([[42., 56., 20., 56., 72.],
       [ 2., 42., 72., 30., 20.],
       [ 6., 42., 42.,  2., 90.]])

In [148]:
# Multiply the ones array with the latest array


array_expo = array_mul ** 2
array_expo

array([[1.764e+03, 3.136e+03, 4.000e+02, 3.136e+03, 5.184e+03],
       [4.000e+00, 1.764e+03, 5.184e+03, 9.000e+02, 4.000e+02],
       [3.600e+01, 1.764e+03, 1.764e+03, 4.000e+00, 8.100e+03]])

In [97]:
# Do the same thing with np.square()


array_expo_1 = np.square(array_expo)
array_expo_1

array([[3.31776000e+09, 9.83449600e+06, 8.10000000e+05, 3.31776000e+09,
        5.47363226e+09],
       [3.11169600e+06, 2.68738560e+07, 1.29600000e+03, 3.31776000e+09,
        2.68738560e+07],
       [1.09719938e+09, 6.56100000e+07, 3.11169600e+06, 0.00000000e+00,
        3.11169600e+06]])

In [102]:
# Find the mean of the latest array using np.mean()

array_mean = np.mean(a11)
array_mean

8.733333333333333

In [103]:
# Find the maximum of the latest array using np.max()


array_max = np.max(a11)
array_max

16

In [104]:
# Find the minimum of the latest array using np.min()


array_min = np.min(a11)
array_min

0

In [105]:
# Find the standard deviation of the latest array

array_std = np.std(a11)
array_std

4.836895239257881

In [106]:
# Find the variance of the latest array


array_var = np.var(a11)
array_var

23.395555555555557

In [107]:
# Reshape the latest array to (3, 5, 1)


array_reshape = a11.reshape(3,5,1)
array_reshape

array([[[15],
        [ 7],
        [ 5],
        [15],
        [16]],

       [[ 6],
        [ 8],
        [ 2],
        [15],
        [ 8]],

       [[13],
        [ 9],
        [ 6],
        [ 0],
        [ 6]]])

In [108]:

# Transpose the latest array

array_reshape.T

array([[[15,  6, 13],
        [ 7,  8,  9],
        [ 5,  2,  6],
        [15, 15,  0],
        [16,  8,  6]]])

In [110]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


ran_arr_1 = np.random.randint(0,10, size =(3,3))
ran_arr_2 = np.random.randint(0,10, size=(3,2))

ran_arr_1


array([[5, 2, 3],
       [3, 2, 9],
       [2, 2, 3]])

In [111]:
ran_arr_2

array([[6, 3],
       [8, 0],
       [7, 6]])

In [149]:
np.dot(ran_arr_1, ran_arr_2)

array([[67, 33],
       [97, 63],
       [49, 24]])

In [112]:
# Perform a dot product on the two newest arrays you created


arr_dot = ran_arr_1.dot(ran_arr_2)
arr_dot

array([[67, 33],
       [97, 63],
       [49, 24]])

In [119]:
arr_dot_1 = ran_arr_2.dot(ran_arr_1)
arr_dot_1

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [118]:
# solving the above error 

arr_dot_1 = ran_arr_2.T.dot(ran_arr_1)
arr_dot_1

array([[ 68,  42, 111],
       [ 27,  18,  27]])

In [120]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


arr_int_1 = np.random.randint(0,10, size= (4,3))
arr_int_2 = np.random.randint(0,10, size= (4,3))
arr_int_1

array([[1, 7, 0],
       [8, 8, 1],
       [6, 9, 2],
       [6, 9, 8]])

In [121]:
arr_int_2

array([[3, 0, 1],
       [0, 4, 4],
       [6, 8, 8],
       [2, 2, 2]])

In [123]:
# Perform a dot product on the two newest arrays you created

arr_int_dot = arr_int_1.T.dot(arr_int_2)
arr_int_dot

array([[ 51,  92,  93],
       [ 93, 122, 129],
       [ 28,  36,  36]])

In [124]:
# Compare the two arrays with '>'

arr_compare = arr_int_1 > arr_int_2
arr_compare 


array([[False,  True, False],
       [ True,  True, False],
       [False,  True, False],
       [ True,  True,  True]])

In [125]:
# Find which elements of the first array are greater than 7 

greater = arr_int_1 > 7
greater 


#true = yes 
#false = no

array([[False, False, False],
       [ True,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [126]:
# Which parts of each array are equal? (try using '==')


equal = arr_int_1 == arr_int_2
equal

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [127]:
# Sort one of the arrays you just created in ascending order


sort = np.sort(arr_int_1)
sort

array([[0, 1, 7],
       [1, 8, 8],
       [2, 6, 9],
       [6, 8, 9]])

In [152]:
# Sort the indexes of one of the arrays you just created 
np.argsort(ran_arr_1)

array([[1, 2, 0],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [153]:

# Find the index with the maximum value in one of the arrays you've created

np.argmax(ran_arr_1)

5

In [154]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(ran_arr_1)


1

In [155]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(ran_arr_1, axis=1)


array([0, 2, 2], dtype=int64)

In [156]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


np.argmin(ran_arr_1, axis=0)

array([2, 0, 0], dtype=int64)

In [157]:
# Create an array of normally distributed random number

np.random.randn(3,5)

array([[ 0.41811852, -1.88652805,  2.27334516,  0.14697465,  0.5396092 ],
       [-1.49829564, -0.01144345,  0.41335409, -0.14089855,  0.87216186],
       [ 1.30034515, -1.34352376,  0.85012058,  0.39433995, -0.00469599]])

In [158]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

Insert the image 

<img src="panda.png"/>

<img src="car-photo.png"/>

In [172]:
# find out the data from the image 
from matplotlib.image import imread
    
panda = imread("panda.png") 
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [174]:
car_photo = imread("car-photo.png")
car_photo[:10]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352